name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install TeX Live
      run:  bash .github/workflows/install-texlive.sh

    - name: Test example
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make
